### ISSUE TITLE
Sermons are out of order

### ISSUE THREAD

**Issue by ArtskydJ** [TehShrike/revelation-visualized#2]
![capture](https://cloud.githubusercontent.com/assets/1833684/24975961/356c8f0c-1f8d-11e7-80b6-297e28506f1b.PNG)

The dates in the files' metadata are in the order that you would expect, so it seems [these lines](https://github.com/TehShrike/revelation-visualized/blob/master/sermon-text-and-audio-correlater/index.js#L58-L60) aren't functioning correctly.

**Comment by TehShrike** [comment]
Good catch, thanks - it now sorts sermons by date when they cover the same verses.
